using System.Collections.Generic;

namespace AreaSurvivors
{
    public static class LocalizationTextCatalog
    {
        static readonly Dictionary<string, string> JapaneseCorrections = new Dictionary<string, string>
        {
            { "木の城壁と木の城門を建造可能にします。", "木の城壁を建造可能にします。" },
            { "壁と門の最大HPを +20 / Lv 上げます。", "壁の最大HPを +20 / Lv 上げます。" },
            { "ゲーム中に壁と門をアップグレード可能にします。", "ゲーム中に壁をアップグレード可能にします。" },
            { "壁②をアップグレード可能にします。", "建造設計の外周にある壁②をアップグレードします。" },
            { "建造物が一定間隔でHPを自動回復します。", "壁・バリスタ・監視塔が2秒ごとにHPを 1 / Lv 自動回復します。" },
            { "建造物の攻撃力 +1", "中心塔とバリスタの攻撃力 +1" },
            { "敵撃破100ごとに攻撃力 +1（最大+10）", "ラン中の敵撃破100体ごとに攻撃力 +1（最大+10）" },
            { "2レベルごとに塗り範囲がさらに1セル広がります。", "2つの「塗り範囲」スキルの合計レベルが2上がるごとに、塗り範囲が1セル広がります。" },
            { "正面の近距離に三日月状の斬撃を放つ、最初から使える基本武器です。", "正面の近距離に三日月状の斬撃を放つ基本武器です。通常は初期装備ですが、永続強化で外すこともできます。" }
        };

        static readonly Dictionary<string, string> English = new Dictionary<string, string>
        {
            { "塗り広げた領地で塔を守り抜け", "Expand your territory. Defend the tower." },
            { "エリアサバイバー", "AREA SURVIVORS" },
            { "プレイ", "PLAY" },
            { "オプション", "OPTIONS" },
            { "クレジット", "CREDITS" },
            { "ゲーム開発\n・しゅんたむ\n\nBGM / 効果音\n本作品では以下のフリー音素材サイトの素材を利用しています。\n各素材の権利は各制作者・配布元に帰属します。\n\n・効果音ラボ\n  https://soundeffect-lab.info/\n・PANICPUMPKIN\n  https://pansound.com/panicpumpkin/\n・ポケットサウンド\n  https://pocket-se.info/", "Game Development\n• Shuntamu\n\nBGM / Sound Effects\nThis game uses assets from the following free audio resource websites.\nRights to each asset belong to its respective creator and distributor.\n\n• Sound Effect Lab\n  https://soundeffect-lab.info/\n• PANICPUMPKIN\n  https://pansound.com/panicpumpkin/\n• Pocket Sound\n  https://pocket-se.info/" },
            { "ゲーム終了", "QUIT GAME" },
            { "閉じる", "CLOSE" },
            { "宝箱を開ける", "OPEN CHEST" },
            { "レリック獲得", "RELIC ACQUIRED" },
            { "レリックが見つかりません", "No relic found" },
            { "建造", "BUILD" },
            { "一般", "GENERAL" },
            { "サウンド", "SOUND" },
            { "グラフィック", "GRAPHICS" },
            { "コントロール", "CONTROLS" },
            { "言語", "Language" },
            { "日本語", "Japanese" },
            { "表示モード", "Display Mode" },
            { "ウィンドウサイズ", "Window Size" },
            { "フルスクリーン", "Fullscreen" },
            { "現在: フルスクリーン", "Current: Fullscreen" },
            { "効果音", "Sound Effects" },
            { "移動", "Move" },
            { "キーボードマウス", "Keyboard & Mouse" },
            { "コントローラー", "Controller" },
            { "決定", "Confirm" },
            { "キャンセル", "Cancel" },
            { "設定初期化", "Reset Settings" },
            { "データ初期化", "Reset Save Data" },
            { "ゲームのプレイデータが全て初期化されますが、実行しますか？", "All gameplay save data will be erased. Continue?" },
            { "戻る", "Back" },
            { "上", "Up" },
            { "下", "Down" },
            { "左", "Left" },
            { "右", "Right" },
            { "左Stick↑", "Left Stick Up" },
            { "左Stick↓", "Left Stick Down" },
            { "左Stick←", "Left Stick Left" },
            { "左Stick→", "Left Stick Right" },
            { "十字↑", "D-Pad Up" },
            { "十字↓", "D-Pad Down" },
            { "十字←", "D-Pad Left" },
            { "十字→", "D-Pad Right" },
            { "ロビー", "LOBBY" },
            { "ゲームスタート", "START GAME" },
            { "強化", "UPGRADES" },
            { "武器図鑑", "WEAPON BOOK" },
            { "所持レリック", "OWNED RELICS" },
            { "タイトルへ", "BACK TO TITLE" },
            { "プレイ回数", "RUNS" },
            { "累計撃破数", "TOTAL KILLS" },
            { "トークン所持数", "TOKENS" },
            { "進行状況", "PROGRESS" },
            { "ナイト", "Knight" },
            { "前方を切り払う", "Slash enemies ahead" },
            { "難易度1", "Difficulty 1" },
            { "テスト起動", "TEST LAUNCHER" },
            { "ロビーへ", "BACK TO LOBBY" },
            { "永続強化", "PERMANENT UPGRADES" },
            { "所持トークン 0", "Tokens: 0" },
            { "プレイヤースキル", "PLAYER SKILLS" },
            { "建造物スキル", "BUILDING SKILLS" },
            { "中心塔スキル", "CENTRAL TOWER SKILLS" },
            { "スキルを選択", "Select a Skill" },
            { "アイコンにカーソルを合わせると強化内容を確認できます。", "Hover over an icon to view its upgrade details." },
            { "レベルアップ", "LEVEL UP" },
            { "一時停止", "PAUSED" },
            { "再開", "RESUME" },
            { "諦める", "GIVE UP" },
            { "獲得したトークンを失いますが、諦めますか？", "You will lose the tokens earned during this run. Give up?" },
            { "スキップ  残り3", "SKIP (3 LEFT)" },
            { "リロール  残り3", "REROLL (3 LEFT)" },
            { "攻撃力", "Attack" },
            { "攻撃間隔", "Cooldown" },
            { "攻撃範囲", "Attack Area" },
            { "爆発範囲", "Blast Radius" },
            { "射程", "Range" },
            { "矢の本数", "Arrows" },
            { "ノックバック", "Knockback" },
            { "シールド数", "Shields" },
            { "回転速度", "Rotation Speed" },
            { "速度低下", "Slow" },
            { "速度低下 ", "Slow " },
            { "速度低下: ", "Slow: " },
            { "剣本数", "Swords" },
            { "攻撃回数", "Hits" },
            { "攻撃距離", "Distance" },
            { "攻撃時間", "Active Time" },
            { "弾数", "Projectiles" },
            { "持続時間", "Duration" },
            { "移動速度", "Move Speed" },
            { "塗り範囲", "Paint Radius" },
            { "復活時間", "Revive Time" },
            { "防御力", "Defense" },
            { "経験値倍率", "XP Multiplier" },
            { "自動回復", "Regeneration" },
            { "説明", "Description" },
            { "効果", "Effect" },
            { "レリック名", "Relic Name" },
            { "ランリザルト", "RUN RESULTS" },
            { "生存時間", "Survival Time" },
            { "到達ステージ", "Stage Reached" },
            { "到達レベル", "Level Reached" },
            { "敵撃破数", "Enemies Defeated" },
            { "獲得トークン", "Tokens Earned" },
            { "取得レリック", "Relics Acquired" },
            { "総ダメージ", "Total Damage" },
            { "総ダメージ / DPS", "Total Damage / DPS" },
            { "ステージ2が解放されました", "Stage 2 unlocked" },
            { "総", "TOTAL" },
            { "武器一覧", "WEAPONS" },
            { "解放した武器の性能と特徴を確認できます", "View the stats and traits of unlocked weapons." },
            { "初期ステータス", "BASE STATS" },
            { "特徴", "TRAITS" },
            { "特殊効果", "SPECIAL EFFECTS" },
            { "進化条件", "EVOLUTION REQUIREMENTS" },
            { "レリック一覧", "RELICS" },
            { "宝箱から獲得した永続強化を確認できます", "View permanent upgrades acquired from chests." },
            { "強化内容", "BONUS" },
            { "コモン", "Common" },
            { "アンコモン", "Uncommon" },
            { "レア", "Rare" },
            { "レジェンダリー", "Legendary" },
            { "スラッシュ", "Slash" },
            { "ソードラッシュ", "Sword Rush" },
            { "バナナ", "Banana" },
            { "弓", "Bow" },
            { "ファイアボール", "Fireball" },
            { "シールド", "Shield" },
            { "旗", "Banner" },
            { "ブーメランソード", "Boomerang Sword" },
            { "オーラソード", "Aura Sword" },
            { "アローレイン", "Arrow Rain" },
            { "銃", "Gun" },
            { "フロスト", "Frost" },
            { "サンダーボール", "Thunder Ball" },
            { "オークキング", "Orc King" },
            { "イノシシ", "Boar" },
            { "エリートイノシシ", "Elite Boar" },
            { "オーク", "Orc" },
            { "エリートオーク", "Elite Orc" },
            { "ゴブリン", "Goblin" },
            { "エリートゴブリン", "Elite Goblin" },
            { "オーガ", "Ogre" },
            { "エリートオーガ", "Elite Ogre" },
            { "ゴブリンロード", "Goblin Lord" },
            { "スケルトン", "Skeleton" },
            { "エリートスケルトン", "Elite Skeleton" },
            { "スケルトンナイト", "Skeleton Knight" },
            { "エリートスケルトンナイト", "Elite Skeleton Knight" },
            { "リッチ", "Lich" },
            { "リザード", "Lizard" },
            { "エリートリザード", "Elite Lizard" },
            { "リザードマン", "Lizardman" },
            { "エリートリザードマン", "Elite Lizardman" },
            { "ドラゴン", "Dragon" },
            { "エリートイノシシ出現！", "Elite Boar Incoming!" },
            { "エリートオーク出現！", "Elite Orc Incoming!" },
            { "オークキング出現！", "Orc King Incoming!" },
            { "エリートゴブリン出現！", "Elite Goblin Incoming!" },
            { "エリートオーガ出現！", "Elite Ogre Incoming!" },
            { "ゴブリンロード出現！", "Goblin Lord Incoming!" },
            { "エリートスケルトン出現！", "Elite Skeleton Incoming!" },
            { "エリートスケルトンナイト出現！", "Elite Skeleton Knight Incoming!" },
            { "リッチ出現！", "Lich Incoming!" },
            { "エリートリザード出現！", "Elite Lizard Incoming!" },
            { "エリートリザードマン出現！", "Elite Lizardman Incoming!" },
            { "ドラゴン出現！", "Dragon Incoming!" },
            { "中心塔", "Central Tower" },
            { "バリスタ", "Ballista" },
            { "監視塔", "Watchtower" },
            { "武器1枠目", "Weapon Slot 1" },
            { "武器2枠目", "Weapon Slot 2" },
            { "武器3枠目", "Weapon Slot 3" },
            { "予備", "Reserve" },
            { "なし", "None" },
            { "選択待ち", "Select a build option" },
            { "ロック", "Locked" },
            { "木", "Wood" },
            { "石", "Stone" },
            { "1 木の城壁", "1 Wooden Wall" },
            { "配置可", "Can Place" },
            { "在庫なし", "Out of Stock" },
            { "資源不足", "Not Enough Resources" },
            { "遠すぎる", "Too Far Away" },
            { "配置不可", "Cannot Place" },
            { "範囲外", "Out of Range" },
            { "青床のみ", "Blue Tiles Only" },
            { "未設定", "Not Configured" },
            { "ウィンドウ", "Windowed" },
            { "カスタム", "Custom" },
            { "壁追加", "Unlock Wooden Wall" },
            { "木の城壁と木の城門を建造可能にします。", "Allows wooden walls to be built." },
            { "木の城壁を建造可能にします。", "Allows wooden walls to be built." },
            { "壁耐久上昇", "Wall Durability" },
            { "壁と門の最大HPを +20 / Lv 上げます。", "Wall max HP +20 per level." },
            { "壁の最大HPを +20 / Lv 上げます。", "Wall max HP +20 per level." },
            { "壁アップグレード", "Wall Upgrade" },
            { "ゲーム中に壁と門をアップグレード可能にします。", "Allows walls to be upgraded during a run." },
            { "ゲーム中に壁をアップグレード可能にします。", "Allows walls to be upgraded during a run." },
            { "壁②追加", "Add Outer Walls" },
            { "建造設計の外周に壁②を追加します。", "Adds a second ring of walls around the outer perimeter." },
            { "壁②アップグレード", "Upgrade Outer Walls" },
            { "壁②をアップグレード可能にします。", "Upgrades the second wall line in the outer construction plan." },
            { "建造設計の外周にある壁②をアップグレードします。", "Upgrades the second wall line in the outer construction plan." },
            { "建造物自動回復", "Structure Regeneration" },
            { "建造物が一定間隔でHPを自動回復します。", "Walls, ballistas, and watchtowers recover 1 HP per level every 2 seconds." },
            { "壁・バリスタ・監視塔が2秒ごとにHPを 1 / Lv 自動回復します。", "Walls, ballistas, and watchtowers recover 1 HP per level every 2 seconds." },
            { "中心塔自動回復", "Central Tower Regeneration" },
            { "中心塔の自動回復量が上昇します。", "Increases the central tower's automatic healing." },
            { "中心塔HP", "Central Tower HP" },
            { "中心塔の最大HPが上昇します。", "Increases the central tower's max HP." },
            { "中心塔大砲", "Central Tower Cannon" },
            { "中心塔が砲撃できるようになります。", "Unlocks cannon fire for the central tower." },
            { "中心塔アップグレード", "Central Tower Upgrade" },
            { "中心塔をアップグレードし、耐久力と防衛性能を高めます。", "Upgrades the central tower, improving durability and defense." },
            { "プレイヤーHP", "Player HP" },
            { "プレイヤーの最大HPが上昇します。", "Increases the player's max HP." },
            { "体力自動回復", "Health Regeneration" },
            { "一定時間ごとにHPを自動回復します。", "Automatically restores HP at regular intervals." },
            { "受けるダメージを軽減します。", "Reduces damage taken." },
            { "復活時間短縮", "Faster Revival" },
            { "復活時間を -0.7秒 / Lv 短縮します。", "Reduces revival time by 0.7 seconds per level." },
            { "経験値獲得量", "XP Gain" },
            { "獲得経験値が上昇します。", "Increases experience gained." },
            { "移動速度が上昇します。", "Increases movement speed." },
            { "移動速度がさらに上昇します。", "Further increases movement speed." },
            { "塗り範囲が1セル広がります。", "Expands paint radius by 1 cell." },
            { "2レベルごとに塗り範囲が1セル広がります。", "Expands paint radius by 1 cell for every 2 combined levels." },
            { "2レベルごとに塗り範囲がさらに1セル広がります。", "Expands paint radius by 1 cell whenever the combined level of both Paint Radius skills increases by 2." },
            { "2つの「塗り範囲」スキルの合計レベルが2上がるごとに、塗り範囲が1セル広がります。", "Expands paint radius by 1 cell whenever the combined level of both Paint Radius skills increases by 2." },
            { "バリスタ追加", "Unlock Ballista" },
            { "バリスタを建造可能にします。", "Allows ballistas to be built." },
            { "バリスタ射程", "Ballista Range" },
            { "バリスタの攻撃射程を広げます。", "Increases ballista attack range." },
            { "バリスタ攻撃力", "Ballista Attack" },
            { "バリスタの攻撃力を上げます。", "Increases ballista attack power." },
            { "バリスタアップグレード", "Ballista Upgrade" },
            { "ゲーム中にバリスタをアップグレード可能にします。", "Allows ballistas to be upgraded during a run." },
            { "監視塔追加", "Unlock Watchtower" },
            { "監視塔を建造可能にします。", "Allows watchtowers to be built." },
            { "監視塔範囲", "Watchtower Paint Radius" },
            { "監視塔の自動塗り範囲を広げます。", "Expands the watchtower's automatic paint area." },
            { "監視塔攻撃力上昇", "Watchtower Damage" },
            { "監視塔の範囲内にいる敵へ与えるダメージを上げます。", "Increases damage dealt to enemies inside watchtower range." },
            { "監視塔アップグレード", "Watchtower Upgrade" },
            { "ゲーム中に監視塔をアップグレード可能にします。", "Allows watchtowers to be upgraded during a run." },
            { "エリート出現数UP", "More Elite Enemies" },
            { "エリート敵の出現数が増えます。", "Increases the number of elite enemies." },
            { "終了時トークン", "End-of-Run Tokens" },
            { "ラン終了時の固定獲得トークンが +1 増えます。", "Increases fixed end-of-run token rewards by 1." },
            { "開幕レベルアップ", "Starting Level Boost" },
            { "ゲーム開始時にプレイヤーのレベルが上がります。最大3回強化するとLv4から開始できます。", "Raises the player's level at the start of a run. At rank 3, begin at level 4." },
            { "開幕宝箱出現", "Starting Relic Chest" },
            { "ゲーム開始時、中心塔の下にレリック宝箱が出現します。", "Spawns a relic chest below the central tower at the start of a run." },
            { "初期スラッシュ削除", "Remove Starting Slash" },
            { "ゲーム開始時にスラッシュを持たず、武器枠を1つ空けた状態にします。", "Start without Slash, leaving one weapon slot empty." },
            { "ボス撃破時建造物復活", "Revive Buildings on Boss Defeat" },
            { "ボス撃破時、破壊された建造物が最大HP50%で復活します。", "Destroyed buildings revive at 50% max HP after defeating a boss." },
            { "塗りエリアトークン獲得", "Painted-Area Tokens" },
            { "塗ったエリアが500に到達する度、スキルレベル分のトークンを獲得します。", "Gain tokens equal to this skill's level whenever painted area reaches another 500." },
            { "弓アンロック", "Unlock Bow" },
            { "ファイアボールアンロック", "Unlock Fireball" },
            { "シールドアンロック", "Unlock Shield" },
            { "アローレインアンロック", "Unlock Arrow Rain" },
            { "銃アンロック", "Unlock Gun" },
            { "フロストアンロック", "Unlock Frost" },
            { "サンダーボールアンロック", "Unlock Thunder Ball" },
            { "旗アンロック", "Unlock Banner" },
            { "ブーメランソードアンロック", "Unlock Boomerang Sword" },
            { "オーラソードアンロック", "Unlock Aura Sword" },
            { "レベルアップ時の候補に弓が登場するようになります。", "Adds Bow to the level-up choices." },
            { "レベルアップ時の候補にファイアボールが登場するようになります。", "Adds Fireball to the level-up choices." },
            { "レベルアップ時の候補にシールドが登場するようになります。", "Adds Shield to the level-up choices." },
            { "レベルアップ時の候補にアローレインが登場するようになります。", "Adds Arrow Rain to the level-up choices." },
            { "レベルアップ時の候補に銃が登場するようになります。", "Adds Gun to the level-up choices." },
            { "レベルアップ時の候補にフロストが登場するようになります。", "Adds Frost to the level-up choices." },
            { "レベルアップ時の候補にサンダーボールが登場するようになります。", "Adds Thunder Ball to the level-up choices." },
            { "レベルアップ時の候補に旗が登場するようになります。", "Adds Banner to the level-up choices." },
            { "レベルアップ時の候補にブーメランソードが登場するようになります。", "Adds Boomerang Sword to the level-up choices." },
            { "レベルアップ時の候補にオーラソードが登場するようになります。", "Adds Aura Sword to the level-up choices." },
            { "移動ペナルティ低下", "Reduced Movement Penalty" },
            { "敵陣地上の移動速度低下を +0.1 / Lv 軽減します。", "Reduces the movement penalty on enemy territory by 0.1 per level." },
            { "石工の打撃符", "Mason's Strike Sigil" },
            { "建造物の攻撃力 +1", "Central tower and ballista attack +1" },
            { "中心塔とバリスタの攻撃力 +1", "Central tower and ballista attack +1" },
            { "討伐者の勲章", "Slayer's Medal" },
            { "敵撃破100ごとに攻撃力 +1（最大+10）", "Attack +1 per 100 enemies defeated this run (max +10)" },
            { "ラン中の敵撃破100体ごとに攻撃力 +1（最大+10）", "Attack +1 per 100 enemies defeated this run (max +10)" },
            { "戦士の護符", "Warrior's Charm" },
            { "古い戦場で使われていた護符。装備者の一撃に迷いをなくします。", "A charm carried on old battlefields. It banishes hesitation from every strike." },
            { "武器攻撃力 +10%", "Weapon attack +10%" },
            { "生命の核", "Vital Core" },
            { "淡く脈打つ結晶。身体の奥から生命力を押し上げます。", "A softly pulsing crystal that draws vitality from deep within the body." },
            { "最大HP +20", "Max HP +20" },
            { "風走りの靴", "Windrunner Boots" },
            { "風を編み込んだ軽い靴。危険地帯を駆け抜けやすくなります。", "Light boots woven with wind, made for racing through danger." },
            { "移動速度 +8%", "Move speed +8%" },
            { "学びのレンズ", "Scholar's Lens" },
            { "経験の流れを見通す小さなレンズ。戦いから多くを学べます。", "A small lens that reveals the flow of experience and lessons hidden in battle." },
            { "経験値獲得量 +10%", "XP gain +10%" },
            { "黄金の印章", "Golden Seal" },
            { "勝利の報酬を呼び込む黄金の印。遠征後の成果が増えます。", "A golden seal that draws greater rewards from every expedition." },
            { "クリア/敗北時トークン +10%", "End-of-run tokens +10%" },
            { "職人の槌跡が刻まれた札。建造物の一撃をわずかに重くします。", "A sigil marked by a mason's hammer, lending extra weight to defensive strikes." },
            { "職人の槌跡が刻まれた札。中心塔とバリスタの一撃をわずかに重くします。", "A sigil marked by a mason's hammer, lending extra weight to the central tower and ballistas." },
            { "剣士の小手", "Swordsman's Gauntlet" },
            { "握りを安定させる革の小手。近接武器の威力を高めます。", "A leather gauntlet that steadies the grip and strengthens melee weapons." },
            { "近接系武器の攻撃力 +1", "Melee weapon attack +1" },
            { "鷹目の羽根", "Hawk-Eye Feather" },
            { "矢筋を読む羽根飾り。遠距離武器の攻撃間隔を短縮します。", "A feather that reads the path of a shot and hastens ranged attacks." },
            { "遠距離系武器の攻撃間隔 -5%", "Ranged weapon cooldown -5%" },
            { "詠唱の砂時計", "Chanting Hourglass" },
            { "砂が落ちるたびに詠唱が整います。魔法武器の攻撃間隔を短縮します。", "Each falling grain steadies the chant and hastens magic attacks." },
            { "魔法系武器の攻撃間隔 -5%", "Magic weapon cooldown -5%" },
            { "守護者の鋲", "Guardian Rivet" },
            { "盾に打ち込まれた古い鋲。防御武器の反撃を強めます。", "An old shield rivet that strengthens the counterattack of defensive weapons." },
            { "防御系武器の攻撃力 +1", "Defensive weapon attack +1" },
            { "刃こぼれ知らず", "Unchipped Edge" },
            { "欠けない刃を象った小さな護符。スラッシュの威力を高めます。", "A tiny charm shaped like an unbreakable blade that empowers Slash." },
            { "スラッシュの攻撃力 +2", "Slash attack +2" },
            { "双矢の矢筒", "Twin-Arrow Quiver" },
            { "二本目の矢が自然に手に馴染む矢筒です。", "A quiver that makes a second arrow feel natural in the hand." },
            { "弓の矢の本数 +1", "Arrows per shot +1" },
            { "火種の指輪", "Ember Ring" },
            { "消えない火種を宿す指輪。ファイアボールの詠唱を早めます。", "A ring holding an undying ember that hastens Fireball casting." },
            { "ファイアボールの攻撃間隔 -5%", "Fireball cooldown -5%" },
            { "巡る盾片", "Orbiting Shield Shard" },
            { "宙を巡る盾の欠片。守りの輪をひとつ増やします。", "A shield fragment that circles through the air, adding another layer of protection." },
            { "シールド数 +1", "Shield count +1" },
            { "鼓舞の紋旗", "Rally Banner Sigil" },
            { "周囲の士気を高める小さな紋章。旗の影響範囲を広げます。", "A small crest that raises fighting spirit and expands the Banner's reach." },
            { "旗の攻撃範囲 +1", "Banner area +1" },
            { "返り刃の輪", "Returning Blade Ring" },
            { "投げた刃を呼び戻す輪。ブーメランソードの本数を増やします。", "A ring that calls thrown blades home and adds another Boomerang Sword." },
            { "ブーメランソードの剣本数 +1", "Boomerang Sword count +1" },
            { "残響の剣印", "Echo Sword Seal" },
            { "斬撃の余韻を残す印。オーラソードの攻撃回数を増やします。", "A seal that preserves the echo of a slash and adds another Aura Sword strike." },
            { "オーラソードの攻撃回数 +1", "Aura Sword strike count +1" },
            { "雨呼びの羽飾り", "Raincaller Plume" },
            { "矢の雨を広げる羽飾り。アローレインの範囲を広げます。", "A plume that spreads a rain of arrows across a wider area." },
            { "アローレインの攻撃範囲 +1", "Arrow Rain area +1" },
            { "黒鉄の弾丸", "Black-Iron Bullet" },
            { "重く黒い弾丸。銃撃に鋭い衝撃を与えます。", "A heavy black bullet that gives every gunshot a sharper impact." },
            { "銃の攻撃力 +2", "Gun attack +2" },
            { "霜広げの結晶", "Frostspread Crystal" },
            { "冷気を薄く広げる結晶。フロストの範囲を広げます。", "A crystal that spreads a thin layer of cold and expands Frost's area." },
            { "フロストの攻撃範囲 +1", "Frost area +1" },
            { "蓄雷の核", "Thunder Core" },
            { "雷を内に溜める小さな核。サンダーボールを長く残します。", "A small core that stores lightning and keeps Thunder Ball active longer." },
            { "サンダーボールの持続時間 +1", "Thunder Ball duration +1" },
            { "旅商人の契約書", "Traveling Merchant Contract" },
            { "戦場で拾った戦利品を商人が買い取る契約書です。", "A contract for a merchant to buy spoils recovered on the battlefield." },
            { "通常敵が2%でトークンを落とす", "Normal enemies have a 2% chance to drop a token" },
            { "調和の紋章", "Harmony Crest" },
            { "異なる武器の力を響き合わせる紋章です。", "A crest that brings the power of different weapon classes into harmony." },
            { "3武器のカテゴリが全て異なる時、攻撃力 +15%", "Attack +15% when all 3 weapon classes are different" },
            { "無傷の誓印", "Unwounded Vow Seal" },
            { "傷ひとつない戦いを誓う印です。", "A seal bearing a vow to finish the battle without a single wound." },
            { "HP最大時、攻撃力 +10%", "Attack +10% at full HP" },
            { "孤高の刃", "Solitary Blade" },
            { "ただ一振りに全てを託す者の刃です。", "A blade for those who entrust everything to a single weapon." },
            { "武器が1つだけの時、攻撃力 2倍", "Attack x2 while carrying only 1 weapon" },
            { "王域の王冠", "Dominion Crown" },
            { "支配した土地の力を中心塔へ集める王冠です。", "A crown that channels the power of claimed land into the central tower." },
            { "塗ったエリアに応じて中心塔の攻撃力上昇（最大2倍）", "Central tower attack rises with painted area (up to x2)" },
            { "支配者の照準器", "Ruler's Sight" },
            { "領域の広がりを弩の狙いへ変える照準器です。", "A sight that turns expanding territory into perfect ballista aim." },
            { "塗ったエリアに応じてバリスタの攻撃力上昇（最大2倍）", "Ballista attack rises with painted area (up to x2)" },
            { "再生する城壁石", "Regenerating Wallstone" },
            { "欠けてもゆっくり形を戻す不思議な石材です。", "A mysterious stone that slowly restores its shape after being chipped." },
            { "壁の自動回復 +3", "Wall regeneration +3" },
            { "倒した敵の数だけ重みを増す勲章です。", "A medal that grows heavier with every enemy defeated." },
            { "このランで倒した敵の数だけ重みを増す勲章です。", "A medal that grows heavier with every enemy defeated during the current run." },
            { "富豪の戦印", "War Seal of Wealth" },
            { "戦場で得た富を力へ変える戦印です。", "A war seal that turns wealth gathered in battle into strength." },
            { "ラン中トークン10ごとに攻撃力 +1（最大+10）", "Attack +1 per 10 tokens gained this run (max +10)" },
            { "三刃王の紋章", "Tri-Blade King's Crest" },
            { "三つの刃を束ねる王の紋章です。近接武器のみで攻める者に豪腕を授けます。", "A royal crest binding three blades, granting might to warriors armed only with melee weapons." },
            { "近接武器3種装備時、攻撃力 +20", "Attack +20 while equipped with 3 melee weapons" },
            { "星弓の照準冠", "Starbow Sight Crown" },
            { "星の軌跡を矢筋へ変える黄金の冠です。遠距離武器の連携を極限まで研ぎ澄まします。", "A golden crown that turns starlight into trajectories and perfects the harmony of ranged weapons." },
            { "遠距離武器3種装備時、攻撃力 +20", "Attack +20 while equipped with 3 ranged weapons" },
            { "三賢魔晶", "Tri-Sage Crystal" },
            { "三人の賢者の魔力が封じられた結晶です。魔法武器のみを揃えた時に深い魔力を解き放ちます。", "A crystal holding the power of three sages, unleashed when wielding only magic weapons." },
            { "魔法武器3種装備時、攻撃力 +10", "Attack +10 while equipped with 3 magic weapons" },
            { "千討の覇勲章", "Thousand-Slayer Laurel" },
            { "幾千の勝利を刻む覇者の勲章です。積み重ねた討伐の記憶が力へ変わります。", "A champion's medal engraved with countless victories, turning remembered triumphs into power." },
            { "累計撃破1000ごとに攻撃力 +1（最大+20）", "Attack +1 per 1,000 total kills (max +20)" },
            { "正面の近距離に三日月状の斬撃を放つ、最初から使える基本武器です。", "A basic weapon that releases a crescent slash at close range. Normally equipped at the start, but a permanent upgrade can remove it." },
            { "正面の近距離に三日月状の斬撃を放つ基本武器です。通常は初期装備ですが、永続強化で外すこともできます。", "A basic weapon that releases a crescent slash at close range. Normally equipped at the start, but a permanent upgrade can remove it." },
            { "進化武器", "Evolved Weapon" },
            { "武器をLv.10にすると進化することができます。", "Reach weapon Lv.10 to unlock its evolution." },
            { "武器Lv.10", "Weapon Lv.10" },
            { "条件を満たすと進化することができます。", "Meet the requirements to unlock its evolution." },
            { "スラッシュを進化させる", "Evolve Slash" },
            { "五月雨の剣撃を5回繰り出す。攻撃力と攻撃範囲が大幅に上昇する。", "Unleashes five rapid sword strikes with greatly increased damage and range." },
            { "ブーメランソードを進化させる", "Evolve Boomerang Sword" },
            { "無数のバナナを周囲へ投げる。剣本数が3本増加し、攻撃範囲が大幅に上昇する。", "Throws a storm of bananas in every direction, adding three projectiles and greatly increasing attack area." },
            { "エクスカリバー", "Excalibur" },
            { "黄金の弓", "Golden Bow" },
            { "アローシャワー", "Arrow Shower" },
            { "マシンガン", "Machine Gun" },
            { "ファイアミサイル", "Fire Missile" },
            { "フロストストーム", "Frost Storm" },
            { "サンダーストーム", "Thunder Storm" },
            { "デュアルシールド", "Dual Shield" },
            { "女神の祝福", "Goddess's Blessing" },
            { "ゲームプレイ回数5回以上", "Play the game at least 5 times" },
            { "ゲームプレイ中の撃破数300", "Defeat 300 enemies during the run" },
            { "レリックを10個以上所持", "Own at least 10 relics" },
            { "ゲームプレイ中の獲得トークン数50", "Gain 50 tokens during the run" },
            { "塗り自陣エリア50%以上", "Control at least 50% of the area" },
            { "プレイヤーLv.30", "Reach player Lv.30" },
            { "ボス出現中", "While a boss is active" },
            { "進化武器を3つ以上アンロック", "Discover at least 3 evolved weapons" },
            { "累計討伐数10000", "Defeat 10,000 enemies in total" },
            { "プレイヤーのHPが満タンではない", "Player HP is not full" },
            { "中心塔のHPが半分以下", "Center tower HP is at or below half" },
            { "オーラソードを進化させる", "Evolve Aura Sword" },
            { "弓を進化させる", "Evolve Bow" },
            { "アローレインを進化させる", "Evolve Arrow Rain" },
            { "銃を進化させる", "Evolve Gun" },
            { "ファイアボールを進化させる", "Evolve Fireball" },
            { "フロストを進化させる", "Evolve Frost" },
            { "サンダーボールを進化させる", "Evolve Thunder Ball" },
            { "シールドを進化させる", "Evolve Shield" },
            { "旗を進化させる", "Evolve Flag" },
            { "前方へ巨大な斬撃を放ち、触れている敵へ持続ダメージを与える。", "Launches a massive forward slash that continuously damages enemies touching it." },
            { "攻撃力が大幅に上昇した金色の矢が、射程内の敵を貫通する。", "Fires greatly empowered golden arrows that pierce enemies within range." },
            { "攻撃時間中、画面内の敵へ範囲ダメージを持つ矢を降らせる。", "Rains area-damaging arrows on enemies visible on screen for the attack duration." },
            { "進行方向へ0.2秒間隔で大量の銃弾を連射する。", "Rapidly fires a barrage of non-piercing bullets forward every 0.2 seconds." },
            { "射程内の敵を追尾する炎の玉を放つ。", "Launches a fiery missile that homes in on an enemy within range." },
            { "画面内の敵5体へ氷のトゲを出現させ、周囲を凍結する。", "Summons ice spikes beneath five visible enemies and freezes the surrounding area." },
            { "雷球を放ちながら、3つの雷球をプレイヤーの周囲に回転させる。", "Launches thunder orbs while three additional orbs circle the player." },
            { "紫色のシールドが倍の数と速度、広い軌道で回転する。", "Purple shields orbit with double the base count, speed, and distance." },
            { "光の魔法陣が敵を攻撃し、プレイヤーと範囲内の建造物を5回復する。", "A radiant magic circle attacks enemies and heals the player and nearby buildings by 5." },
            { "進行方向へ敵を貫通する強力な銃弾を発射します。", "Fires powerful, piercing bullets straight ahead." },
            { "進行方向45度範囲のランダム方向に斬撃を飛ばします。", "Launches slashes in random directions within a 45-degree arc ahead." },
            { "着弾地点で爆発する火球を放ち、まとまった敵に範囲ダメージを与えます。", "Launches a fireball that explodes on impact and damages groups of enemies." },
            { "進行方向の先に矢の雨を降らせ、範囲内の敵へ継続ダメージを与えます。", "Calls down a rain of arrows ahead, dealing continuous damage in an area." },
            { "プレイヤーの周囲に追従する円状の床を展開し、床上の敵にダメージと速度低下を与えます。", "Creates a circular field around the player that damages and slows enemies." },
            { "進行方向に回転する剣を投げ、一定距離で反対方向へ戻る近接武器です。", "Throws a spinning sword that returns after traveling a set distance." },
            { "進行方向の少し先に氷のエリアを作り、敵にダメージと速度低下を与えます。", "Creates an icy area ahead that damages and slows enemies." },
            { "離れた敵を狙って矢を放つ遠距離武器です。射程が長く、敵に近づかれる前に削れます。", "A long-range weapon that targets distant enemies before they can close in." },
            { "進行方向に近い敵をゆっくり追尾する雷球を放ち、持続中は周囲にダメージを与え続けます。", "Launches a slow homing thunder orb that continuously damages nearby enemies." },
            { "プレイヤーの周囲を回転するシールドを展開し、触れた敵にダメージとノックバックを与えます。", "Deploys rotating shields that damage and knock back enemies on contact." },
            { "エリア占有率が70%以上の時、攻撃力２倍", "70% area control: Attack x2" },
            { "エリア占有率が50%以上の時、エリア取得範囲に応じて攻撃範囲拡大", "50% area control: Attack area scales with paint radius" },
            { "エリア占有率が50%以上の時、爆発範囲２倍", "50% area control: Blast radius x2" },
            { "エリア占有率が70%以上の時、剣本数２倍", "70% area control: Sword count x2" },
            { "エリア占有率が50%以上の時、射程２倍", "50% area control: Range x2" },
            { "エリア占有率が70%以上の時、攻撃範囲２倍", "70% area control: Attack area x2" },
            { "エリア占有率が50%以上の時、ノックバック２倍", "50% area control: Knockback x2" },
            { "エリア占有率が50%以上の時、回転速度２倍", "50% area control: Rotation speed x2" },
            { "テスト用データ操作", "TEST DATA" },
            { "ステージ開始", "START STAGE" },
            { "ボス出現位置指定", "BOSS SPAWN POSITION" },
            { "テスト操作を選択できます", "Choose a test action." },
            { "ストーリー再生", "PLAY STORY" },
            { "テストメニューへ戻る", "BACK TO TEST MENU" },
            { "ゲーム起動テスト", "GAMEPLAY TESTS" },
            { "レリック取得状態", "RELIC OWNERSHIP" },
            { "全レリックを未取得へ", "MARK ALL RELICS UNOWNED" },
            { "強化状態を初期化", "RESET UPGRADES" },
            { "武器進化確認済み状態を初期化", "RESET WEAPON EVOLUTIONS" },
            { "クリア状態を初期化", "RESET CLEAR STATUS" },
            { "トークン +99999", "TOKENS +99999" },
            { "製品版ビルドではテスト操作は利用できません", "Test actions are unavailable in production builds." },
            { "トークンを +99999 しました", "Added 99,999 tokens." },
            { "強化状態を初期化しました", "Upgrade progress reset." },
            { "武器進化確認済み状態を初期化しました", "Weapon evolution discoveries reset." },
            { "ステージクリア状態を初期化しました", "Stage clear status reset." },
            { "クリア済みにしました", "Marked as cleared." },
            { "未クリアに戻しました", "Marked as not cleared." },
            { "取得済", "Owned" },
            { "未取得", "Not owned" },
            { "全レリックを未取得に戻しました", "Marked all relics as not owned." },
            { "【取得済】", "[Owned]" },
            { "切替: ", "Toggle: " },
            { "未取得に戻す: ", "Mark unowned: " },
            { "クリア済", "Cleared" },
            { " / クリア: ", " / Clear: " },
            { "未確認", "Unknown" },
            { "トークン 0\n累計撃破 0", "Tokens 0\nTotal Kills 0" },
            { "  ［変更］", "  [CHANGE]" },
            { "自動攻撃（変更不可）", "Auto Attack (Not Rebindable)" },
            { "入力待ち", "Waiting for input" },
            { "再入力", "Try Again" },
            { "上方向", "Up" },
            { "下方向", "Down" },
            { "左方向", "Left" },
            { "右方向", "Right" },
            { "ボタンのみ", "Buttons Only" },
            { "特殊効果は今後追加予定です。", "Special effects will be added in a future update." },
            { "予定", "PLANNED" },
            { "スキップ 残り{0}", "SKIP ({0} LEFT)" },
            { "リロール 残り{0}", "REROLL ({0} LEFT)" },
            { "レリック変換: トークン +{0}", "Relic converted: +{0} tokens" },
            { "新規武器：", "New weapon: " },
            { "を獲得", " acquired" },
            { "門番の知らせを受け、ナイトは跳ね起きた。", "Warned by the gatekeeper, the knight sprang awake." },
            { "ナイトは塔を守るため、戦場へ駆け出した。", "The knight rushed to the battlefield to defend the tower." },
            { "変換トークン +", "Converted tokens +" },
            { "すでに獲得済みのため、トークン +{0} に変換されました。", "Already owned. Converted into +{0} tokens." },
            { "未取得のレリックです。ゲーム中に宝箱を拾うと獲得できます。", "This relic is not owned. Find it in a chest during a run." },
            { "取得済みレリックはまだありません。ゲーム中に宝箱を拾うと、ここに追加されます。", "No relics owned yet. Relics found in chests will appear here." },
            { "{0}  実装予定", "{0}  PLANNED" },
            { "（現在はツリー上の予約ノードです）", " (reserved for a future update)" },
            { "スキルツリーでアンロックが必要です", "Unlock this weapon in the skill tree." },
            { "武器パネルを選択してください。", "Select a weapon panel." },
            { "回転半径: ", "Orbit Radius: " },
            { "弾速: ", "Projectile Speed: " },
            { "セル", " cells" },
            { "秒", "s" },
            { "ステージ{0}が解放されました", "Stage {0} unlocked" },
            { "取得リリック", "Relics Acquired" },
            { "ストーリーを見届けたナイトは、塔を守るため戦場へ向かう。", "The knight rushes to the battlefield to defend the tower." },
            { "静かな塔の中で、ナイトは眠りについていた。", "Inside the quiet tower, the knight slept peacefully." },
            { "門番は夜の平原に、ただならぬ気配を感じ取る。", "The gatekeeper sensed something moving across the night plains." },
            { "イノシシの大群が、中心塔へ向かって押し寄せる。", "A massive herd of boars charged toward the central tower." },
        };

        static readonly KeyValuePair<string, string>[] EnglishReplacements =
        {
            new KeyValuePair<string, string>("星弓の照準冠", "Starbow Sight Crown"),
            new KeyValuePair<string, string>("鼓舞の紋旗", "Rally Banner Sigil"),
            new KeyValuePair<string, string>("再生する城壁石", "Regenerating Wallstone"),
            new KeyValuePair<string, string>("石工の打撃符", "Mason's Strike Sigil"),
            new KeyValuePair<string, string>("【未取得】", "[Not owned]"),
            new KeyValuePair<string, string>(" を取得済みにしました", " marked as owned."),
            new KeyValuePair<string, string>(" を未取得に戻しました", " marked as not owned."),
            new KeyValuePair<string, string>(" は既に取得済みです", " is already owned."),
            new KeyValuePair<string, string>(" は既に未取得です", " is already not owned."),
            new KeyValuePair<string, string>(" の取得状態を変更できませんでした", " ownership could not be changed."),
            new KeyValuePair<string, string>("キー入力中", " - press a key"),
            new KeyValuePair<string, string>(" は使用中です", " is already in use"),
            new KeyValuePair<string, string>(" を", " "),
            new KeyValuePair<string, string>("ステージ、武器、レリック、強化データを指定して動作確認できます", "Configure stage, weapon, relic, and upgrade data for testing."),
            new KeyValuePair<string, string>("各ステージのボス直前から開始し、上下左右の指定位置にボスを出現させます", "Start before each stage boss and choose its spawn direction."),
            new KeyValuePair<string, string>("武器別 STAGE 1 開始", "START STAGE 1 BY WEAPON"),
            new KeyValuePair<string, string>("ボス直前開始", "START BEFORE BOSS"),
            new KeyValuePair<string, string>("テスト開始", "START TEST"),
            new KeyValuePair<string, string>("未クリア", "NOT CLEARED"),
            new KeyValuePair<string, string>("出現！", " Incoming!"),
            new KeyValuePair<string, string>("（変換）", " (converted)"),
            new KeyValuePair<string, string>("ステージ", "Stage "),
            new KeyValuePair<string, string>("難易度", "Difficulty "),
            new KeyValuePair<string, string>("現在: ", "Current: "),
            new KeyValuePair<string, string>("所持トークン", "Tokens: "),
            new KeyValuePair<string, string>("攻撃力", "Attack"),
            new KeyValuePair<string, string>("攻撃間隔", "Cooldown"),
            new KeyValuePair<string, string>("攻撃範囲", "Area"),
            new KeyValuePair<string, string>("残り", "left"),
            new KeyValuePair<string, string>("右", "Right"),
            new KeyValuePair<string, string>("左", "Left"),
            new KeyValuePair<string, string>("上", "Up"),
            new KeyValuePair<string, string>("下", "Down")
        };

        static readonly KeyValuePair<string, string>[] OrderedEnglish = BuildOrderedEnglish();

        public static string Translate(string source, GameLanguage language)
        {
            if (string.IsNullOrEmpty(source)) return source;

            if (language == GameLanguage.Japanese)
            {
                string japanese = JapaneseCorrections.TryGetValue(source, out string corrected) ? corrected : source;
                return NormalizeUpgradeArrow(japanese);
            }

            if (English.TryGetValue(source, out string english)) return english;
            if (!ContainsJapanese(source)) return NormalizeUpgradeArrow(source);

            string result = source;
            foreach (var replacement in EnglishReplacements)
            {
                if (result.Contains(replacement.Key)) result = result.Replace(replacement.Key, replacement.Value);
            }

            foreach (var pair in OrderedEnglish)
            {
                if (result.Contains(pair.Key)) result = result.Replace(pair.Key, pair.Value);
            }

            return NormalizeUpgradeArrow(result);
        }

        static bool ContainsJapanese(string value)
        {
            for (int i = 0; i < value.Length; i++)
            {
                char character = value[i];
                if ((character >= '\u3040' && character <= '\u30ff')
                    || (character >= '\u3400' && character <= '\u9fff')
                    || (character >= '\uff66' && character <= '\uff9d')) return true;
            }

            return false;
        }

        static string NormalizeUpgradeArrow(string value)
        {
            if (string.IsNullOrEmpty(value) || value.IndexOf('<') >= 0) return value;
            return value.Replace(">", " → ");
        }

        static KeyValuePair<string, string>[] BuildOrderedEnglish()
        {
            var entries = new List<KeyValuePair<string, string>>(English);
            entries.Sort((left, right) => right.Key.Length.CompareTo(left.Key.Length));
            return entries.ToArray();
        }
    }
}
